### ISSUE TITLE
How to include other npm packages?

### ISSUE THREAD

**Issue by ap1969** [stackbithq/stackbit-theme-azimuth#10]
Hi, 
I've forked the project so I can add a couple of components that I'd like to add, mainly in the footer. However, what I'd like to do is add material-ui icons to the site (running on Gatsby).

Is this possible? I can't see any way to import the module during the build process.

Regards,
Andy

**Comment by smnh** [comment]
@ap1969 you should first use app.stackbit.com to generate Gatsby site from Azimuth theme.
Then, Stackbit will generate for you a repo with this theme converted to Gatsby site. In this repo you will be able to use your Gatsby/React skills to import any modules you like :)
