### ISSUE TITLE
Footer missing .site-logo class, results in improper spacing on iPhone X

### ISSUE THREAD

**Issue by grempe** [stackbithq/stackbit-theme-azimuth#8]
I've modified the file:

https://github.com/stackbithq/stackbit-theme-azimuth/blob/master/sass/imports/_footer.scss#L94

to include a `.site-logo` class:

```
.footer-branding {
  a {
    border: 0;
  }

  .site-title {
    font-size: 1.33333rem;

    &:last-child {
      margin-bottom: 2.5rem;
    }
  }

  .site-description {
    margin: 0.5rem 0 2.5rem;
  }

  .site-logo {
    margin-bottom: 2.5rem;
  }
}

```

This class is applied to the logo in the footer, but was apparently not defined. This leads to no spacing between the logo and the company secondary menu title on iPhone.

**Comment by grempe** [comment]
This particular fix does cause the footer tagline to drop too low below the logo though, so it needs to be tweaked.

**Comment by TomasBankauskas** [comment]
Hey @grempe,

thank you for reporting. You did everything right, just you need to use :last-child pseudo-class selector:

```
.footer-branding {
  .site-logo {
    &:last-child {
      margin-bottom: 2.5rem;
    }
  }
}
```
I've fixed the issue.
